### PR TITLE
perform_has_many_through implemented

### PR DESCRIPTION
**Pull request by diegonogueira**
I implemented a possible solution for has_many through. :)

### CODE REVIEW

**Comment by tapickell** [comment]
@diegonogueira  Is this how a developer would use this in the schema/types on one of the objects associated in a join_through ?
```
object :stack do
    ...
    field :team_members, list_of(:team_member), resolve: assoc(:team_members_stacks)
end
```

**Comment by diegonogueira** [comment]
Yes @tapickell. You can use like has_many :)

**Comment by diegonogueira** [comment]
@tapickell You can use something like this:

```
object :stack do
    ...
    field :team_members, list_of(:team_member), resolve: assoc(:team_members)
end
```

**Comment by tapickell** [comment]
@diegonogueira thanks I am able to move forward using your fork until a solution is merged into master. :+1:

**Comment by benwilson512** [comment]
Hey! I appreciate the PR, but in the end I think we're going to try to just leverage the functions that Ecto gives us to handle this instead of re-creating a bunch of ecto logic, which is what this path (and the path I was originally on) are gonna end  up having to do.

**Pull request closed without merging**
